apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 80