apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    name: mem-stress
    image: polinux/stress
    resources:
      limits:
        memory: "20Mi"
      requests:
        memory: "5Mi"